version: "3.7"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    container_name: "${PROJECT_NAME}_nginx_proxy"
    environment:
      DEFAULT_HOST: $PROJECT_BASE_URL
    networks:
      - plams-network
    ports:
      - "80:80"
      - "443:443"
#      - "9944:9944"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/nginx/vhost.d
      - ./nginx/certs/:/etc/nginx/certs:rw
      - /usr/share/nginx/html
#      - ./nginx/proxy.conf:/etc/nginx/proxy.conf
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"

  openssl:
    build:
      context: ./dockerfiles/openssl
      dockerfile: Dockerfile
#    image: pgarrett/openssl-alpine
    container_name: "${PROJECT_NAME}_openssl"
    networks:
      - plams-network
    environment:
      LETSENCRYPT_EMAIL: $LETSENCRYPT_EMAIL
      LETSENCRYPT_HOST: $PROJECT_BASE_URL
      DEFAULT_EMAIL: $LETSENCRYPT_EMAIL
      COUNTY: $COUNTY
      STATE: $STATE
      LOCATION: $LOCATION
      ORGANISATION: $ORGANISATION
      ISSUER_CN: $ISSUER_CN
      PUBLIC_CN: $PUBLIC_CN
      ISSUER_NAME: $ISSUER_NAME
      PUBLIC_NAME: $PUBLIC_NAME
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./nginx/certs:/etc/ssl/certs:rw
    volumes_from:
      - nginx-proxy

  plasm:
#    Build from ubuntu 18.04 lts + rustup + make from binaries plasm-node
    build:
      context: ./dockerfiles/plasmnode
      dockerfile: Dockerfile
      args:
        PLASM_GROUP: $PLASM_GROUP
        PLASM_USER: $PLASM_USER
        PLASM_VER: $PLASM_VER
        NIGHTLY_VER: $NIGHTLY_VER
    image: "smakisog/plasm:${PLASM_VER}"
    container_name: "${PROJECT_NAME}_node"
    restart: unless-stopped
    tty: true
    networks:
      - plams-network
    environment:
      VIRTUAL_HOST: $PROJECT_BASE_URL
#      VIRTUAL_PORT: 9944
      LETSENCRYPT_HOST: 'plasmukraine.northeurope.cloudapp.azure.com'
      LETSENCRYPT_EMAIL: $LETSENCRYPT_EMAIL
    volumes:
      - $NODE_DB_PATH:/home/plasmnode
    volumes_from:
      - nginx-proxy
    entrypoint: ["plasm-node", "--base-path", "/home/plasmnode/db", "--validator", "--name", $NODE_NAME, "--rpc-cors", "all", "--in-peers", "50", "--out-peers", "50"]

networks:
  plams-network:
    external:
      name: plams-network